/******************************|
|********** PCT ***************|
|******************************/
----- CONSULTA 

Select * from TOEPFERDB.TBLPCTCABECERA where CDPEDIDO in ('AS-121-13')
Select * from TOEPFERDB.TBLPCTCABECERA where IDPEDIDO in (1302)
Select * from TOEPFERDB.TBLPCTCOTIZACIONES where IDPEDIDO=1454
Select * from TOEPFERDB.TBLPCPDETALLE where IDPEDIDO=1450
Select * from TOEPFERDB.TBLPCTBINARYFILES where IDPEDIDO=1439
Select * from TOEPFERDB.TBLDATOSOBRAS  where CDOBRA='1332'
Select * from TOEPFERDB.TBLBUDGETOBRAS where IDOBRA=306
----- CAMBIO DE ESTADO
--Update TOEPFERDB.TBLPCTCABECERA set ESTADO=15, FECHACIERRE=20111222 where CDPEDIDO='ET-T-145-11'
Update TOEPFERDB.TBLPCTCABECERA set ESTADO=22 where IDPEDIDO in (1450)
Update TOEPFERDB.TBLPCTCABECERA set CDSOLICITANTE='MAD' where CDPEDIDO='EX-001-13'
Update TOEPFERDB.TBLPCTCABECERA set IDOBRA = 28, IDAREA=0, IDDETALLE=0 where IDPEDIDO=1415
--Update TOEPFERDB.TBLPCTCABECERA set FECHAINICIO=20110407, FECHACIERRE=20110428, momento=20110507165713, ESTADO=21 where IDPEDIDO=526
Update TOEPFERDB.TBLPCTCOTIZACIONES set IDPROVEEDOR=25974 where IDPEDIDO=1360 and IDPROVEEDOR=24577
Update TOEPFERDB.TBLPCPDETALLE set IDPROVEEDOR=25974 where IDPEDIDO=1345 and IDPROVEEDOR=24577

Delete from TOEPFERDB.TBLPCTCOTIZACIONES where IDPEDIDO=1454 and IDCOTIZACION=5210

/******************************|
|********** PCP ***************|
|******************************/
-- CONSULTA

Select * from TOEPFERDB.TBLPCPCABECERA where IDPEDIDO=1434
Select * from TOEPFERDB.TBLPCPDETALLE where IDPEDIDO=1469 --and NROSOBRE=3
Select * from TOEPFERDB.TBLPOLIZASCAUCION where IDPEDIDO=1287 

Update TOEPFERDB.TBLPCPDETALLE set CDMONEDA='P' where IDPEDIDO=1469 --and NROSOBRE=3

Insert into TOEPFERDB.TBLPOLIZASCAUCION (IDPEDIDO,	TIPO, IMPORTE,	CDMONEDA	,	ESTADO,	CDUSUARIO,	MMTO) values(1287, 'A', 115817550, 'P', 1, 'MMZ', '20130701150000')
-- FIRMAS

Select * from TOEPFERDB.TBLPCPFIRMAS where IDPEDIDO in (1308)
Select * from TOEPFERDB.TBLPCPFIRMAS where IDPEDIDO in (1420, 1428, 1431, 1342)
Select * from TOEPFERDB.TBLPCTCABECERA where IDPEDIDO in (1420, 1428, 1431, 1342)

Delete from TOEPFERDB.TBLPCPFIRMAS where CDUSUARIO='NO_3'

/******************************|
|********** PIC ***************|
|******************************/
----- CONSULTA
Select * from TOEPFERDB.TBLCTZCABECERA where IDCOTIZACION in (7737)
Select * from TOEPFERDB.TBLCTZCABECERA where IDPROVEEDOR= 17011
Select * from TOEPFERDB.TBLCTZDETALLE where IDCOTIZACION in (13194, 13208, 13615, 13927)
Select * from TOEPFERDB.TBLCTZFIRMAS where IDCOTIZACION in (13898)
Select * from TOEPFERDB.TBLCTZAJUSTES where IDCOTIZACION in (11599)
Select * from TOEPFERDB.TBLCTZAJUSTESFIRMAS where IDAJUSTE in (704)
Select * from PROVFL.ACD7REP where NINGX7 in (695953)
Select * from PROVFL.ACDSREP where DSQFNB in (423072)

Update TOEPFERDB.TBLCTZCABECERA set IDOBRA=306 where IDCOTIZACION = 12438
Update TOEPFERDB.TBLCTZCABECERA set IDCONTRATO=1 where IDCOTIZACION in (7151) --and IDARTICULO=4444
Update TOEPFERDB.TBLCTZCABECERA set IDPROVEEDOR=25728 where IDCOTIZACION=11810
Update TOEPFERDB.TBLCTZCABECERA set IMPORTEPESOS=IMPORTEPESOS+1 where IDCOTIZACION=13041
Update TOEPFERDB.TBLCTZDETALLE set CANTIDAD=7 where IDCOTIZACION=13559 and IDARTICULO=7046
Update TOEPFERDB.TBLCTZCABECERA set ESTADO='F' where IDCOTIZACION in (7737)
Update TOEPFERDB.TBLCTZCABECERA set CDMONEDA='D' where IDCOTIZACION=12583
Update TOEPFERDB.TBLCTZDETALLE set IDARTICULO=5270 where IDCOTIZACION=13191 and IDARTICULO=10437
Update TOEPFERDB.TBLCTZCABECERA set IMPORTEPESOS=192000, IMPORTEDOLARES=42600 where IDCOTIZACION=7737
Update TOEPFERDB.TBLCTZDETALLE set IMPORTEPESOS=3360000, IMPORTEDOLARES=550729 where IDCOTIZACION=14306 and IDARTICULO=9664-- and IDAREA=13
Update TOEPFERDB.TBLCTZDETALLE set FACTURADO=(CANTIDAD*IMPORTEPESOSFACTURADO)/IMPORTEPESOS where IDCOTIZACION in (14262) --and IDARTICULO=4444
Update TOEPFERDB.TBLCTZDETALLE set IMPORTEPESOSFACTURADO= IMPORTEPESOSFACTURADO+3831596, IMPORTEDOLARESFACTURADO=IMPORTEDOLARESFACTURADO+827380 where IDCOTIZACION in (1798)
Update PROVFL.ACD7REP set COTIX7=74 where NINGX7 in (311451, 311547)
Update PROVFL.ACD7REP set ARTIX7=8835 where NINGX7 in (695953)
Update PROVFL.ACD7REP set AREAX7=10, DETAX7=41 where NINGX7=418121 --and ARTIX7=1024
Update PROVFL.ACD7REP set IMPOX7=8495.62, PRECX7=346.76 where NINGX7=62586
Update PROVFL.ACD7REP set PRECX7=401.48, PREDX7=68.94, CANTX7=7 where COTIX7=13559

--Insert into TOEPFERDB.TBLCTZDETALLE values(3801, 8752, 100, 1, 2232555, 550840, 4.053, 0, 1013, 1015, 0, 0, 0, 0, 0)
--Insert into TOEPFERDB.TBLCTZDETALLE values(3801, 8958, 100, 1, 1180234, 291200, 4.053, 0, 1013, 1015, 0, 0, 0, 0, 0)
Insert into PROVFL.ACD7REP values(687844, 2729, 0.023, 4	, 28, 1002, 1003, 390999.59, 16999982.17, 84430.92, 3670909.57, 21, '', '', '', '')
Insert into PROVFL.ACD7REP values(687844, 2729, 1, 8410	, 28, 1002, 1003, 1172.98, 1172.98, 253.29, 253.29, 0, '', '', '', '')
Insert into PROVFL.ACD7REP values(687844, 1798, 0.003, 8835, 28, 1002, 1004, 38315.96, 12771986.66, 8273.8, 2759733.33, 21, '', '', '', '')
Insert into PROVFL.ACD7REP values(687844, 1798, 1, 8410	, 28, 1002, 1004, 114.94, 114.94, 24.82, 24.82, 0, '', '', '', '')

Delete from TOEPFERDB.TBLCTZDETALLE where IDCOTIZACION=7737 and IDARTICULO=7582
----- FIRMAS

--Select * from TOEPFERDB.TBLCTZFIRMAS where IDCOTIZACION in (518) and CDUSUARIO='JLP'
Update TOEPFERDB.TBLCTZFIRMAS set FECHAFIRMA=null, HKEY='' where IDCOTIZACION in (13898) and CDUSUARIO='JLP'

----- Determinar PICs con cantidades facturadas mal calculadas

Select Distinct PIC.IDCOTIZACION
from TOEPFERDB.TBLCTZCABECERA C inner join TOEPFERDB.TBLCTZDETALLE PIC on C.IDCOTIZACION=PIC.IDCOTIZACION
                                inner join (Select COTIX7, ARTIX7, sum(IMPOX7) IMPOX7 from PROVFL.ACD7REP group by COTIX7, ARTIX7) FAC on PIC.IDCOTIZACION=FAC.COTIX7 and PIC.IDARTICULO=FAC.ARTIX7
where C.ESTADO in ('0', '1', '2')
    and (CANTIDAD*PIC.IMPORTEPESOSFACTURADO)/PIC.IMPORTEPESOS <> FACTURADO    


--Consulta de PICs no finalizados y totalmente pagados.
Update TOEPFERDB.TBLCTZCABECERA set ESTADO='F' where IDCOTIZACION in (
Select CAB.IDCOTIZACION from
(Select * from TOEPFERDB.TBLCTZCABECERA where ESTADO in ('0', '1', '2') and CDMONEDA='D') CAB
inner join (Select IDCOTIZACION, SUM(IMPORTEDOLARESFACTURADO) TOTAL_DETALLE from TOEPFERDB.TBLCTZDETALLE group by IDCOTIZACION) DET on CAB.IDCOTIZACION=DET.IDCOTIZACION
where CAB.IMPORTEDOLARES=DET.TOTAL_DETALLE
)
/******************************|
|********** AFE ***************|
|******************************/
----- CONSULTA
Select * from TOEPFERDB.TBLDATOSAFE where CDAFE='13-ARG-ET-068'
--Select * from TOEPFERDB.TBLDATOSAFE where IDPEDIDO in (583, 593, 609, 611)
Select * from TOEPFERDB.TBLAFEFIRMAS where IDAFE in (622)
Select * from TOEPFERDB.TBLAFEFIRMAS where IDAFE=619
Select * from TOEPFERDB.TBLAFEFIRMAS where CDUSUARIO='GFL' and (HKEY is Null or HKEY='')

Update TOEPFERDB.TBLDATOSAFE set IDOBRA=319 where IDAFE=654
Update TOEPFERDB.TBLDATOSAFE set TITULO='DUCTS AND FALLS REPAIRS' where IDAFE=642
Update TOEPFERDB.TBLDATOSAFE set DESCRIPCION='Metallic repair of transportation ducts and falls in the following áreas:<br><br>Loading scale: three ducts repair and scale coating<br>Truck Discharge: one duct repair<br>Storage: eight ducts, four falls and other metallic structures<br>Loading and berth: four ducts and shiploaders coverage 1 and 3<br>Conditioning plant: one duct.<br><br>This expense was included into the Budget 2013 within the Project Code 2013-Arg-AS-055 (USD 163.057.-)' where IDAFE=642
Update TOEPFERDB.TBLDATOSAFE set CONFIRMADO='N' where IDAFE=610
Update TOEPFERDB.TBLDATOSAFE set TIPO='C', TIPOCC='A' where IDAFE=653
--Update  TOEPFERDB.TBLAFEFIRMAS set CDUSUARIO='MRA' where IDAFE in (347) and CDUSUARIO='ACR'
Update TOEPFERDB.TBLAFEFIRMAS Set CDUSUARIO='JGB' where CDUSUARIO='GFL' and (HKEY is Null or HKEY='')

/******************************|
|********* FACTURAS  **********|
|******************************/
--Select * from TFFL.TF100F1 where FCCMDV=6 and FCCMNR=322
--Select * from TFFL.TF101F1 where FDRGNR=22096 --and FDLNNR=6--FCCMNR=152
--Update TFFL.TF101F1 set FDDETA='11 003 EC01 004004 P' where FDRGNR=22002 and FDLNNR=8
--Select * from TFFL.TF118 where FENRRG=22110
--Update TFFL.TF118 set FENPDE='11040EC01001120M' where FENRRG=22110

/******************************|
|********* CONTRATOS **********|
|******************************/
Select * from TOEPFERDB.TBLOBRACONTRATOS where IDCONTRATO=194
Select * from TOEPFERDB.TBLOBRACONTRATOS where IDPEDIDO=1345
Select * from TOEPFERDB.TBLOBRACONTRATOS where CDCONTRATO in ('27')
Select * from MERFL.MER1C2F1 where MONETC=2 and FECHTC <= 20110905 order by FECHTC desc
Select * from TOEPFERDB.TBLCTCPARTIDAS where IDCONTRATO=50
Select * from TOEPFERDB.TBLDATOSOBRAS where IDOBRA=168

Update TOEPFERDB.TBLOBRACONTRATOS set FECHAVTO=20131231, ESTADO=20 where IDCONTRATO in (136)
Update TOEPFERDB.TBLOBRACONTRATOS set IDAREA=0, IDDETALLE=0 where IDCONTRATO in (189)
Update TOEPFERDB.TBLOBRACONTRATOS set IDOBRA=323 where IDCONTRATO in (194)
Update TOEPFERDB.TBLOBRACONTRATOS SET IDPROVEEDOR=25974 where IDPEDIDO=1360
Update TOEPFERDB.TBLCTCPARTIDAS set FECHACIERRE=20131231, ESTADO=1 where IDCONTRATO=136
Update TOEPFERDB.TBLOBRACONTRATOS SET IMPORTEPESOS=296715436, IMPORTEDOLARES=49784469 where IDCONTRATO=194

Delete from TOEPFERDB.TBLCONTRATOSCONF where NUMERO=6846
Delete from TOEPFERDB.TBLCTCPARTIDAS where IDCONTRATO=189 and IDAREA=6



/******************************|
|*********   VALES   **********|
|******************************/

Select * from TOEPFERDB.TBLVALESCABECERA where NRVALE in ('13-2-002940')
Select * from TOEPFERDB.TBLVALESCABECERA where CDVALE in ('XRS')
Select * from TOEPFERDB.TBLVALESCABECERA where IDVALE = 25498
Select * from TOEPFERDB.TBLVALESDETALLE where IDVALE=27617
Select * from TOEPFERDB.TBLVALESFIRMAS where IDVALE=27618
Select * from TOEPFERDB.TBLARTICULOSDATOS WHERE IDARTICULO in (11013) and IDALMACEN=1
Select * from TOEPFERDB.TBLARTICULOSPRECIOS WHERE IDARTICULO in (375) and IDDIVISION=3 and MMTOPRECIO>=20110613000000

Update TOEPFERDB.TBLVALESCABECERA set CDUSUARIO='DDP' where IDVALE = 27649
Update TOEPFERDB.TBLVALESFIRMAS set CDUSUARIO='DDP' where IDVALE = 27649 and SECUENCIA=0

Insert into TOEPFERDB.TBLVALESFIRMAS values(25498, 2, 'RPS', null, null)

/******************************|
|*********  REMITOS  **********|
|******************************/

Select * from TOEPFERDB.TBLREMCABECERA where NROREMITO like '%6430%'
Select * from TOEPFERDB.TBLREMCABECERA where IDALMACEN=0
Select * from TOEPFERDB.TBLREMDETALLE where IDREMITO in (3957)
Select * from TOEPFERDB.TBLREMPIC where IDPIC=13559

Insert into TOEPFERDB.TBLREMPIC values(0, 8226, 0, 0)

Select DISTINCT PICD.IDCOTIZACION from TOEPFERDB.TBLCTZDETALLE PICD
inner join TOEPFERDB.TBLCTZCABECERA PICC on PICC.IDCOTIZACION=PICD.IDCOTIZACION
inner join TOEPFERDB.TBLARTICULOS ART on PICD.IDARTICULO=ART.IDARTICULO
inner join TOEPFERDB.TBLARTCATEGORIAS CAT on ART.IDCATEGORIA=CAT.IDCATEGORIA
where TIPOCATEGORIA='B'
and PICC.ESTADO='F'
/******************************|
|*********  HEFESTO  **********|
|******************************/

Select * from TOEPFERDB.TBLSYSPRODUCTOS
Select * from TOEPFERDB.TBLSYSREQUERIMIENTOS where IDREQUERIMIENTO=221
Select * from TOEPFERDB.TBLSYSTAREAS where IDREQUERIMIENTO=221
Select * from TOEPFERDB.TBLSYSARCHIVOSAPRODUCCION where IDREQUERIMIENTO=161 and IDTAREA=1483

Select * from TOEPFERDB.TBLSYSFIRMAS where IDREQUERIMIENTO=221 and IDTAREA=1494
Select * from TOEPFERDB.TBLSYSFIRMAS where MMTO >= 20130704000000 and MMTO <= 20130706235959 and SECUENCIA=1
Select * from TOEPFERDB.TBLSYSVERSIONES where IDPRODUCTO=49

Update TOEPFERDB.TBLSYSREQUERIMIENTOS set IDPRODUCTO=49 where IDREQUERIMIENTO=208
Update TOEPFERDB.TBLSYSARCHIVOSAPRODUCCION set CDUSUARIO='CNA' where IDREQUERIMIENTO=161 and IDTAREA=1482
Update TOEPFERDB.TBLSYSFIRMAS set HKEY = null, MMTO = Null where IDREQUERIMIENTO=92 and IDTAREA=1448
Update TOEPFERDB.TBLSYSFIRMAS set MMTO = 20131028131000, HKEY='08021389' where IDREQUERIMIENTO=221 and IDTAREA=1500 and SECUENCIA=2
Update TOEPFERDB.TBLSYSVERSIONES set MAYOR=4, REVISION=0 where IDVERSION=111
Update TOEPFERDB.TBLSYSARCHIVOSAPRODUCCION set IDTAREA=1483 where SVN=2163



Delete from TOEPFERDB.TBLSYSFIRMAS  where IDREQUERIMIENTO=92 and IDTAREA=1448 and SECUENCIA>=2


Select * from TOEPFERDB.TBLSYSVERSIONES
Select * from TOEPFERDB.TBLSYSREQUERIMIENTOS
Select * from TOEPFERDB.TBLSYSVERSIONES
Select IDTAREA, F.IDREQUERIMIENTO, DSPRODUCTO, CONCAT(MAYOR, CONCAT('.', CONCAT(MENOR, CONCAT(' R', RELEASED)))) from TOEPFERDB.TBLSYSFIRMAS F
inner join TOEPFERDB.TBLSYSREQUERIMIENTOS R on R.IDREQUERIMIENTO=F.IDREQUERIMIENTO
inner join TOEPFERDB.TBLSYSPRODUCTOS P on P.IDPRODUCTO=R.IDPRODUCTO
inner join TOEPFERDB.TBLSYSVERSIONES V on V.IDVERSION=R.IDVERSION
WHERE secuencia=1 AND mmto >= 20130101000000
order by F.IDTAREA
/******************************|
|********* GENERALES **********|
|******************************/

--Select * from TOEPFERDB.TBLARTICULOS where IDARTICULO=4444

--Update hoperativos set CDOPERATIVO = '172255606625', NUCARTAPORTE = '172255606625' where CDOPERATIVO like '%17225568%'
--Select * from hvagones where CDOPERATIVO like '%17225560%'
--Update HCALADADEVAGONES set CDOPERATIVO = '172255606625', NUCARTAPORTE = '172255606625' where CDOPERATIVO like '%17225568%'
--Select * from HCALADADEVAGONES where CDOPERATIVO like '%17225568%'


/*
Select PIC.IDCOTIZACION, IDARTICULO, CANTIDAD, PIC.IMPORTEPESOS, IMPOX7 , PIC.IMPORTEPESOSFACTURADO, FACTURADO, (CANTIDAD*PIC.IMPORTEPESOSFACTURADO)/PIC.IMPORTEPESOS REAL, FACTURADO-(CANTIDAD*PIC.IMPORTEPESOSFACTURADO)/PIC.IMPORTEPESOS DIFF
from TOEPFERDB.TBLCTZCABECERA C inner join TOEPFERDB.TBLCTZDETALLE PIC on C.IDCOTIZACION=PIC.IDCOTIZACION
                                inner join (Select COTIX7, ARTIX7, sum(IMPOX7) IMPOX7 from PROVFL.ACD7REP group by COTIX7, ARTIX7) FAC on PIC.IDCOTIZACION=FAC.COTIX7 and PIC.IDARTICULO=FAC.ARTIX7
where C.ESTADO in ('0', '1', '2')
    and (CANTIDAD*PIC.IMPORTEPESOSFACTURADO)/PIC.IMPORTEPESOS <> FACTURADO
*/

--Update TOEPFERDB.TBLCTZDETALLE set FACTURADO=0 where PIC left join PROVFL.ACD7REP FAC on PIC.IDCOTIZACION=FAC.COTIX7 and PIC.IDARTICULO=FAC.ARTIX7
--where IMPOX7 is NULL

--Update TOEPFERDB.TBLVALESDETALLE set VLUPESOS=996, VLUDOLARES=253 where IDVALE=6482 and IDARTICULO=2811
--Select * from TOEPFERDB.TBLARTICULOSDATOS where IDARTICULO=2811
--Select * from TOEPFERDB.TBLARTICULOSPRECIOS where IDARTICULO=2811
--Update TOEPFERDB.TBLARTICULOSPRECIOS set VLUPESOS=996, VLUDOLARES=253, TIPOCAMBIO=3.939 where MMTOPRECIO = 20110119000000 and IDARTICULO=2811
--Update TOEPFERDB.TBLPCTCOTIZACIONES Set CDUSRAPERTURA='FAR', FECHAAPERTURA=20110301163743 Where IDPEDIDO=424 and IDCOTIZACION=1495
--Select * from TOEPFERDB.TBLCTZDETALLE where IDCOTIZACION=2967
--Select * from CAMIONES where CDCHAPACAMION like '%IAS%'
--Insert into TOEPFERDB.TBLARTICULOSPRECIOS values (20110119000000, 3, 2811, 876, 244, 3.614, 20110119000000, 876, 244, 2772)
--Select * from TOEPFERDB.TBLCTZDETALLE where IDCOTIZACION=2772
--Update TOEPFERDB.TBLPCTCABECERA set ESTADO=15 where IDPEDIDO=397
--Update TOEPFERDB.TBLPCTCOTIZACIONES set CDUSRAPERTURA='FREY', FECHAAPERTURA=20110224112000 where IDPEDIDO=397
--Update TOEPFERDB.TBLPCTCOTIZACIONES set CDUSRAPERTURA=null, FECHAAPERTURA=null where IDPEDIDO=397


--Update TOEPFERDB.TBLPCTCOTIZACIONES set IDPEDIDO=-397 where IDPEDIDO=397 and IDCOTIZACION in (1443, 1444)
--Select * from TOEPFERDB.TBLPCTBINARYFILES where IDPEDIDO=397
/*
SELECT r.idobra , r.fecha , r.idareaOrigen idareaOrigen , r.iddetalleOrigen iddetaOrigen , r.idareaDestino idareaDestino , r.iddetalleDestino iddetaDestino, origen.dsBudget detaOrigen, destino.dsBudget detaDestino , r.importepesos , r.importedolares , r.tipocambio , r.motivo , r.cdusuario, r.periodo 
FROM toepferdb.TBLBUDGETREASIGNACION r 
    INNER JOIN toepferdb.tblbudgetObras origen ON r.idobra = origen.idobra and r.idareaorigen = origen.idarea and r.iddetalleorigen = origen.iddetalle 
    INNER JOIN toepferdb.tblbudgetObras destino ON r.idobra = destino.idobra and r.idareaDestino = destino.idarea and r.iddetalledestino = destino.iddetalle 
WHERE r.idobra = 97 AND r.fecha <= 20110131 ORDER BY r.idobra , r.momento DESC , idareaorigen, iddetalleorigen
*/

--Update toepferdb.TBLBUDGETREASIGNACION r set PERIODO=0 WHERE r.idobra = 97 and PERIODO is null
--Select * from TOEPFERDB.TBLDATOSOBRAS
--Update toepferdb.TBLBUDGETOBRAS set CDCUENTA=50310020 WHERE idobra in (96, 97, 98) and IDAREA=12 and IDDETALLE=1
--Select * from TOEPFERDB.TBLPCTCABECERA where CDPEDIDO='LPB-T-002-11'
--Delete from TOEPFERDB.TBLPCTCOTIZACIONES where IDPEDIDO=397
/*
SELECT SUM(EXISTENCIA) STOCK_NUEVO, SUM(VLUPESOS * EXISTENCIA) AS PRECIO_PESOS, SUM(VLUDOLARES * EXISTENCIA) AS PRECIO_DOLARES, AVG(TIPOCAMBIO) AS TIPOCAMBIO, AP.IDDIVISION
FROM (Select * from TOEPFERDB.TBLARTICULOSPRECIOS WHERE IDARTICULO IN (4611, 4612) fetch first 1 row )
     INNER JOIN (Select IDDIVISION, IDARTICULO, SUM(EXISTENCIA) EXISTENCIA from TOEPFERDB.TBLALMACENES AL INNER JOIN TOEPFERDB.TBLARTICULOSDATOS AD on AD.IDALMACEN=AL.IDALMACEN WHERE IDARTICULO IN (4611, 4612) group by IDDIVISION, IDARTICULO) ST
      on AP.IDDIVISION=ST.IDDIVISION and AP.IDARTICULO=ST.IDARTICULO
WHERE AP.IDARTICULO IN (4611, 4612)
GROUP BY AP.IDDIVISION
*/
--Select * from PROVFL.ACD7REP where NINGX7 in (311745, 311890, 311991, 311975, 311976)
--Select * from PROVFL.ACDSREP where DSQFNB in (311745, 311890, 311991, 311975, 311976)
--Insert into PROVFL.ACD7REP values(311745, 0, 1, 4, 28, 1016, 1020, 3900, 3900, 1011.67, 1011.67, 21, '', '', '', '')
--Insert into PROVFL.ACD7REP values(311890, 0, 1, 4, 28, 1016, 1020, 3900, 3900, 1002.57, 1002.57, 21, '', '', '', '')
--Insert into PROVFL.ACD7REP values(311991, 0, 1, 4, 28, 1016, 1017, 14162, 14162, 3639.68, 3639.68, 21, '', '', '', '')
--Insert into PROVFL.ACD7REP values(311975, 0, 1, 4, 28, 1016, 1017, 5970, 5970, 1533.12, 1533.12, 21, '', '', '', '')
--Insert into PROVFL.ACD7REP values(311976, 0, 1, 4, 28, 1013, 1015, 10402, 10402, 2671.5, 2671.50, 21, '', '', '', '')

--Select * from TOEPFERDB.TBLREMPIC where IDPIC=2806
--Select * from PROVFL.ACD7REP where COTIX7=2806
--Select * from PROVFL.ACDSREP where DSQFNB=62781
--Select * from TOEPFERDB.VWCOMPROBANTES where DSQFNB=62781
--Select * from TOEPFERDB.TBLCTZCABECERA where IDCOTIZACION=1072
--Select * from TOEPFERDB.TBLCTZCABECERA where IDCOTIZACION=1072

--Select * from TESFL.TES960F1 where (WCNPRO= 6387 or WCPRET= 6387) order by WCFPAG desc
--Select * from TESFL.TES134F1 where MTNING=403740


/*CAMBIO A EJECUTAR PARA CAMBIAR LA TABLA DE LOS PIC */
--Select * from TOEPFERDB.TBLDATOSAFE where CDAFE='11-ARG-ET-031'
--Select * from TOEPFERDB.TBLPCTCABECERA where IDPEDIDO=294

--Update TOEPFERDB.TBLCTZDETALLE set CANTIDAD=10 where IDCOTIZACION=2776
--Update TOEPFERDB.TBLCTZCABECERA set IDPEDIDO=414 where IDCOTIZACION=2960
--SELECT trimestre, idarea , iddetalle, mes , SUM(gasto) gasto FROM ( SELECT CAST((CAST(SUBSTR(cab.momento,5,2) AS INTEGER)-1)/3 AS INTEGER) trimestre, cab.idbudgetarea idarea , cab.idbudgetdetalle iddetalle, SUBSTR(cab.momento,5,2) mes , SUM(det.vludolares*det.cantidad) gasto FROM toepferdb.tblvalescabecera cab INNER JOIN toepferdb.tblvalesdetalle det ON cab.idvale = det.idvale WHERE cab.idobra = 96 AND cab.estado = 1 AND cab.fecha <= 20110217 GROUP BY CAST((CAST(SUBSTR(cab.momento,5,2) AS INTEGER)-1)/3 AS INTEGER), cab.idbudgetarea , cab.idbudgetdetalle , SUBSTR(cab.momento,5,2) UNION SELECT CAST((CAST(SUBSTR(acds.DSCQDT,4,2) AS INTEGER)-1)/3 AS INTEGER) trimestre, acd7.areax7 idarea , acd7.detax7 iddetalle, SUBSTR(acds.DSCQDT,4,2) mes , SUM(impdx7) gasto FROM provfl.acd7rep acd7 INNER JOIN TOEPFERDB.VWCOMPROBANTES acds ON acd7.NINGX7 = acds.DSQFNB INNER JOIN toepferdb.tblarticulos art on art.idarticulo=acd7.artix7 INNER JOIN toepferdb.tblartcategorias cat on art.idcategoria=cat.idcategoria WHERE acd7.obrax7 = 96 and cat.tipocategoria <> 'I' AND acds.DSCQDT <= 1110217 GROUP BY CAST((CAST(SUBSTR(acds.DSCQDT,4,2) AS INTEGER)-1)/3 AS INTEGER), acd7.areax7 , acd7.detax7 , SUBSTR(acds.DSCQDT,4,2) UNION SELECT CAST((CAST(SUBSTR(cab.momento,5,2) AS INTEGER)-1)/3 AS INTEGER) trimestre , det.idarea , det.iddetalle , SUBSTR(cab.momento,5,2) mes , SUM(det.IMPORTEDOLARES) gasto FROM toepferdb.tblctzcabecera cab INNER JOIN toepferdb.tblctzdetalle det ON cab.idcotizacion = det.idcotizacion WHERE cab.idobra = 96 AND cab.estado IN ('1','2') AND cab.momento <= 20110217595959 GROUP BY det.idarea , det.iddetalle , SUBSTR(cab.momento,5,2), CAST((CAST(SUBSTR(cab.momento,5,2) AS INTEGER)-1)/3 AS INTEGER) ) aux GROUP BY trimestre, idarea , iddetalle, mes ORDER BY idarea , iddetalle, trimestre, mes

--Delete from TOEPFERDB.TBLPCTBINARYFILES where FILENO=1434

--Select * from HCAMIONESDESCARGA where DTCONTABLE='2011-04-01' and NUCARTAPORTE like '%13579920%'

--Update HCAMIONESDESCARGA set CDCOSECHA = 20032004 where DTCONTABLE='2003-03-18' and NUCARTAPORTE='000100565470'

--ALTER TABLE TOEPFERDB.TBLARTICULOS ADD COLUMN MMTOULTIMACOMPRA FOR MMUCR1 BIGINT NOT HIDDEN ADD COLUMN VLUPESOSULTIMACOMPRA FOR VUCPR1 BIGINT NOT HIDDEN ADD COLUMN VLUDOLARESULTIMACOMPRA FOR VUCDR1 BIGINT NOT HIDDEN ADD COLUMN IDPIC FOR CPICR1 INTEGER NOT HIDDEN DEFAULT 0 ;

--Select * from TOEPFERDB.TBLCTZFIRMAS where CDUSUARIO='SMM' and HKEY is NULL--='N'-- and ESTADO <= 30
--Update TOEPFERDB.TBLCTZFIRMAS Set CDUSUARIO='PAC' where CDUSUARIO='SMM' and HKEY is NULL
--Select * from TOEPFERDB.TBLCTZCABECERA where IDCOTIZACION=2967

--Delete from TOEPFERDB.TBLARTICULOSPRECIOS where MMTOPRECIO > 20110101000000
--Update TOEPFERDB.TBLARTICULOSPRECIOS set MMTOPRECIO=20110101000000 where MMTOPRECIO >= 20110301000000
--Select * from TOEPFERDB.TBLARTCATEGORIAS

--Select * from TOEPFERDB.TBLDIVISIONES
--INSERT INTO TOEPFERDB.TBLARTICULOSPRECIOS VALUES(20110331065141,3, 6071, 2675, 667, 4.007, 20110330151513, 6071, 2675, 3220)
--INSERT INTO TOEPFERDB.TBLARTICULOSPRECIOS VALUES(20110331065141,3, 9626, 6750, 1685,4.007, 20110330151513, 9626, 6750, 3220)
--INSERT INTO TOEPFERDB.TBLARTICULOSPRECIOS VALUES(20110331065141,3, 9665,5880,1467,4.007, 20110330151513, 5880,1467, 3220)
--INSERT INTO TOEPFERDB.TBLARTICULOSPRECIOS VALUES(20110331065141,3, 10224,21600,5391,4.007, 20110330151513, 21600,5391, 3220)
--INSERT INTO TOEPFERDB.TBLARTICULOSPRECIOS VALUES(20110331115558,4, 7741,5200,1299,4.004, 20110329145003, 5200,1299, 3204)
--INSERT INTO TOEPFERDB.TBLARTICULOSPRECIOS VALUES(20110331111217,3, 8609,9390,2345,4.004, 20110331064536, 9390,2345, 3205)
--Select * from TOEPFERDB.TBLCTZDETALLE where IDCOTIZACION in (3220, 3204, 3205)
--and IDREMITO in (Select IDREMITO from TOEPFERDB.TBLREMCABECERA VC where VC.FECHA>=20110101)

--Update TOEPFERDB.TBLVALESDETALLE set VLUPESOS=0, VLUDOLARES=0 where IDVALE in (Select IDVALE from TOEPFERDB.TBLVALESCABECERA VC where VC.FECHA>=20110101)
--Select VC.IDVALE, CDVALE, IDARTICULO, IDALMACEN from TOEPFERDB.TBLVALESCABECERA VC inner join TOEPFERDB.TBLVALESDETALLE VD on VC.IDVALE=VD.IDVALE where VC.FECHA>=20110101 and Existencia>0 and VLUPESOS=0 and CDVALE in ('VMS', 'AJS', 'AJU', 'VMT', 'VMR', 'AJT') order by VC.IDVALE--and VD.IDARTICULO in 

--Select * from TOEPFERDB.TBLPMDETALLE

--Select * from PROVFL.ACD7REP --where NINGX7=77588
--Update TOEPFERDB.TBLCTZCABECERA set IDOBRA=72 where IDCOTIZACION=3370
--Select * from TOEPFERDB.TBLCTZDETALLE where IDCOTIZACION=3370
--Update TOEPFERDB.TBLCTZDETALLE set IMPORTEPESOSFACTURADO=7848996, IMPORTEDOLARESFACTURADO=1956744, FACTURADO= 49.762 where IDCOTIZACION=2032
--Insert into PROVFL.ACD7REP values (77588, 0, 1, 4, 28, 1023, 1024, 1032039.56, 1032039.56, 256280, 256280, 0, '', '', '', '')
--Insert into PROVFL.ACD7REP values (77369, 0, 1, 4, 28, 1023, 1025, 36162, 36162, 9000, 9000, 0, '', '', '', '')
--Insert into PROVFL.ACD7REP values (60463, 0, 1, 4, 28, 1023, 1025, 825930, 8259030, 210000, 210000, 0, '', '', '', '')


--Select * from PROVFL.ACDWREP where DWQFNB in (77588, 77369, 60463)

--Select * from PROVFL.ACD7REP where COTIX7=2032

--Update TOEPFERDB.TBLARTICULOSPRECIOS set MMTOPRECIO=20101231235959 where MMTOPRECIO=20110101000000 --IDARTICULO=8020 and IDDIVISION=4
--Select * from TOEPFERDB.TBLREMDETALLE where IDREMITO in (1608, 1315, 1350, 1465)
--Select IDCOTIZACION, C.IDARTICULO, C.CANTIDAD, D.* from TOEPFERDB.TBLCTZDETALLE C left join TOEPFERDB.TBLREMPIC D on C.IDCOTIZACION=D.IDPIC and C.IDARTICULO=D.IDARTICULO where IDCOTIZACION in (352, 481, 3455, 3790, 3609, 4768, 2120, 2239, 3147, 320, 706, 2030, 2512, 2752, 721)
--Select * from TOEPFERDB.TBLCTZCABECERA where IDCOTIZACION=2733
--Select * from TOEPFERDB.TBLARTICULOSDATOS where IDARTICULO=8750 and IDALMACEN=2
--Select * from TOEPFERDB.TBLCIERRESARTICULOS where IDARTICULO=8020 and FECHACIERRE>=20101231 and IDALMACEN=3-- and EXISTENCIA=66
--Select * from TOEPFERDB.TBLREMDETALLE where CANTIDAD>0 and EXISTENCIA=0 and SOBRANTE=0 --and idremito in (1315, 1350, 1608)

--Update TOEPFERDB.TBLARTICULOSDATOS set EXISTENCIA=167, SOBRANTE=500 where IDARTICULO in (8020) and IDALMACEN=3
--Update TOEPFERDB.TBLREMDETALLE set EXISTENCIA=1 where IDREMITO=1608 and IDARTICULO=8750
--Update TOEPFERDB.TBLCIERRESARTICULOS set EXISTENCIA=0, SOBRANTE=114 where IDARTICULO=8738 and FECHACIERRE>=20101231 and IDALMACEN=3 and EXISTENCIA=114

--Insert into TOEPFERDB.TBLREMPIC values (0, 721, 0, 0)

--Insert into TOEPFERDB.TBLARTICULOSDATOS values(8750, 1, 0, 'SYNC', 20110408110306, 2, 0, 0, 0, 0, '')
--Insert into TOEPFERDB.TBLARTICULOSPRECIOS values (20110408110306, 3, 8750, 85994, 21504, 3.999,20110408110306, 85994, 21504, 3172)
--Select * from TOEPFERDB.TBLALMACENES
--Select * from TOEPFERDB.TBLARTICULOSPRECIOS where MMTOPRECIO >= 20110101000000 and IDARTICULO in (
--Select * from TOEPFERDB.TBLCTZCABECERA
--Select IDALMACEN, IDARTICULO, count(*) from TOEPFERDB.TBLVALESCABECERA VC inner join TOEPFERDB.TBLVALESDETALLE VD on VC.IDVALE=VD.IDVALE where FECHA>=20110101 group by IDALMACEN, IDARTICULO
--Select * from TOEPFERDB.TBLARTICULOSDATOS where IDALMACEN=1 --and IDARTICULO=4119

--SQL para determinar proveedores con alguna factura eitida.
/*
Select  Distinct NROPRO "ID", RAZSOC "Razon Social", DOMICI "Domicilio", LOCALI "Localidad", CODPOS "C.Postal", TELEFO "TELEFONO", NRODOC "CUIT"
from TFFL.TF100F1 F inner join MERFL.TCB6A1F1 A on A.NROPRO=F.FCCLNR where FCCMFC >= 20100101 and TIPROV<>'X' and FCCMTF=' '
*/
--SQL para determinar Proveedores con movimientos 
/*
Select A.* from    
       (        
       (Select Distinct APNPRO, 'P' TIPO from TESFL.TES111F1 
         where APFPAG>=20090101 and APPGCB='P' and APNPRO not in (Select Distinct APNPRO from TESFL.TES111F1 where APFPAG>=20090101 and APPGCB='C'))          
        union
        (Select Distinct APNPRO, 'P/C' TIPO from TESFL.TES111F1 
         where APFPAG>=20090101 and APPGCB='P' and APNPRO in (Select Distinct APNPRO from TESFL.TES111F1 where APFPAG>=20090101 and APPGCB='C'))
        union
        (Select Distinct APNPRO, 'C' TIPO from TESFL.TES111F1 
         where APFPAG>=20090101 and APPGCB='C' and APNPRO not in (Select Distinct APNPRO from TESFL.TES111F1 where APFPAG>=20090101 and APPGCB='P'))
    ) Movimientos 
    inner join MERFL.TCB6A1F1 A on A.NROPRO=Movimientos.APNPRO
where TIPROV<>'X'
order by A.NROPRO
*/
/*
Select IDPROV "ID Proveedor", RAZSOC "Razon Social", NRODOC "CUIT/CUIL", DOMICI "Domicilio", LOCALI "Localidad", CODPOS "C.Postal", TELEFO "Telefono", TIPO from TOEPFERDB.TEMPPRV A inner join MERFL.TCB6A1F1 B on B.NROPRO=A.IDPROV
where B.TIPROV<>'X'
order by A.IDPROV
*/
--where IDPROVEEDOR is not NULL
--Select * from toepferdb.tblmailscompras where IDEMPRESA between 1 and 100000
/*
    Select Distinct IDPROVEEDOR, MAIL from toepferdb.tblmailsmercaderias where IDPROVEEDOR>0 
    union 
    Select Distinct IDEMPRESA IDPROVEEDOR, EMAIL MAIL from TOEPFERDB.TBLmailscompras where IDEMPRESA between 1 and 100000
*/
--Select * from TOEPFERDB.TBLARTICULOS where IDARTICULO=8932
--Select * from TOEPFERDB.TBLARTICULOSDATOS where IDARTICULO=8993
--Select * from TOEPFERDB.TBLCIERRESARTICULOS where IDARTICULO=8993 and IDALMACEN=2
--Select * from TOEPFERDB.TBLREMDETALLE where IDARTICULO=8993
--Select * from TOEPFERDB.TBLVALESDETALLE where IDARTICULO=8993
--Select * from TOEPFERDB.TBLVALESCABECERA where IDVALE in (7319, 7480)
--Select * from TOEPFERDB.TBLARTCATEGORIAS

--Select * from TOEPFERDB.TBLARTICULOSPRECIOS where MMTOPRECIO=20110101000000
--Select * from TOEPFERDB.TBLALMACENES
--Select * from MERFL.MER341F2 where PLCPRO=17 and PLNCTO=89432

--Select STOCKFISICO from TOEPFERDB.TBLVALESMAESTRO WHERE CDTIPO='AJS
--Delete from TOEPFERDB.TBLPCTCOTIZACIONES where IDPEDIDO=475 and IDCOTIZACION>=1633 --and IDCOTIZACION=1641
--Update TOEPFERDB.TBLPCTCOTIZACIONES set PATHCOTIZACION='coti.doc' where IDPEDIDO=487 and IDCOTIZACION=1643
--Select * from TOEPFERDB.TBLPCTBINARYFILES where FILENO=1632
--Update TOEPFERDB.TBLCTZDETALLE set IMPORTEPESOS=51698578, IMPORTEDOLARES=12979809 where IDCOTIZACION=2960

--Select * from TOEPFERDB.TBLREMPIC where IDPIC in (3446, 3451)
--Select * from TOEPFERDB.TBLCTZDETALLE where IDCOTIZACION in (3446, 3451)
--Select * from TOEPFERDB.TBLARTICULOSDATOS where IDARTICULO in (4639, 4643)

--Select * from TOEPFERDB.TBLCTZDETALLE where IDCOTIZACION=3466
--Select * from PROVFL.ACD7REP where COTIX7=3466

--Select * from TOEPFERDB.TBLOBRACONTRATOS where IDCONTRATO=66
--Select * from TOEPFERDB.TBLOBRAPAGOS where IDCONTRATO=66

--Update TOEPFERDB.TBLOBRAPAGOS set PORCENTAJE=2.27 where IDCONTRATO=66
--Delete from TOEPFERDB.TBLOBRAPAGOS where IDCONTRATO=66
--Select * from TOEPFERDB.TBLOBRAPAGOS where IDCONTRATO=66
--Update TOEPFERDB.TBLOBRACONTRATOS set CDCONTRATO='A CONFIRMAR', ESTADO=10, ARCHIVO = null where IDCONTRATO=66
--select * from MERFL.MER1C2F1 where MONETC=2 and FECHTC <= 20110517 order by FECHTC desc 
--Select * from TOEPFERDB.TBLCTZCABECERA  where IDCOTIZACION=2586
--Select * from TOEPFERDB.TBLCTZDETALLE  where IDCOTIZACION=2586

/*-------------------------------------------------------------------------*/
--Select * from TOEPFERDB.TBLCIERRESARTICULOS where SOBRANTE < 0
--Select * from TOEPFERDB.TBLALMACENES

--Select * from TOEPFERDB.TBLARTICULOSDATOS where IDALMACEN=3 and IDARTICULO=6530
--Select * from TOEPFERDB.TBLCIERRESARTICULOS where IDALMACEN=2 and IDARTICULO=2787




/* VER ESTO PARA ARREGLAR LA MERGEITEMS PARA CUANDO HAY TRANSFERENCIAS O PRESTAMOS EN CURSO (SE DEBE CONTROLAR QUE ESTO NO OCURRA PARA PODER UNIFICAR, SE UTILIZAN LAS SQL DEL TABLERO DE ALMACENES)
SELECT * 
FROM   ( SELECT PMC.*                         ,
               PMD.*                          ,
               ART.*                          ,
               TG.PARTIDAPENDIENTE AS PARTPEND,
               TG.IDARTICULO                  ,
               TG.SALDOTOTAL
       FROM    ( SELECT  T1.PARTIDAPENDIENTE,
                        T1.IDARTICULO       ,
                        SUM(T1.SALDO) AS SALDOTOTAL
               FROM     ( SELECT  VC1.PARTIDAPENDIENTE,
                                 VD1.IDARTICULO       ,
                                 VC1.CDVALE           ,
                                 CASE(VC1.CDVALE)
                                          WHEN 'VMT'
                                          THEN SUM(VD1.CANTIDAD) 
                                          WHEN 'VMR'
                                          THEN SUM(-VD1.CANTIDAD)
                                          WHEN 'AJT'
                                          THEN SUM(-VD1.CANTIDAD)
                                 END SALDO
                        FROM     TOEPFERDB.TBLVALESCABECERA VC1 
                                 INNER JOIN TOEPFERDB.TBLVALESDETALLE VD1
                                 ON       VC1.IDVALE = VD1.IDVALE 
                        WHERE    VC1.CDVALE IN ('VMT',
                                                'VMR', 
                                                'AJT')
                                AND      VC1.ESTADO=1
                        GROUP BY VC1.PARTIDAPENDIENTE,
                                 VD1.IDARTICULO      ,
                                 VC1.CDVALE
                        ) T1
               GROUP BY T1.PARTIDAPENDIENTE,
                        T1.IDARTICULO
               HAVING   SUM(T1.SALDO) > 0
               ) TG
               INNER JOIN TOEPFERDB.TBLPMCABECERA PMC
               ON      TG.PARTIDAPENDIENTE=PMC.IDPEDIDO
               INNER JOIN TOEPFERDB.TBLPMDETALLE PMD
               ON      PMC.IDPEDIDO  =PMD.IDPEDIDO
               AND     PMD.IDARTICULO=TG.IDARTICULO
               INNER JOIN TOEPFERDB.TBLARTICULOS ART
               ON      ART.IDARTICULO=TG.IDARTICULO
      ) TAB 
WHERE  ( TAB.IDALMACEN    = 2 OR TAB.IDALMACENDEST= 2 )
ORDER BY TAB.PARTPEND
*/
----------------------------------------------------------------------------------------
-- SQL para chequear que no se produzcan diferencias entre los importes del presupuesto TOTAL y de los parciales trimestrales.
/*
Select * from   TOEPFERDB.TBLBUDGETOBRAS A 
                Left join 
                (Select IDOBRA, IDAREA, IDDETALLE, sum(PSBUDGET) IMPORTEPESOS, sum(DLBUDGET) IMPORTEDOLARES from TOEPFERDB.TBLBUDGETOBRASDETALLE group by IDOBRA, IDAREA, IDDETALLE) B
                 on A.IDOBRA=B.IDOBRA and A.IDAREA=B.IDAREA and A.IDDETALLE=B.IDDETALLE
where A.DLBUDGET <> B.IMPORTEDOLARES --or A.PSBUDGET <> B.IMPORTEPESOS
Order by A.IDOBRA, A.IDAREA, A.IDDETALLE
*/
/*-- Query para Mercaderías - Extraer montos de las finales y algunos conceptos específicos (15, 24, 65, 66)
Select BASE.*, I15, I24, I65, I66 from 
(Select Distinct CPROCC, CSUCCC,COPECC,NCTOCC, ACOSCC, NCOMCC from MERFL.MER331F1 
where CPROCC=17 and ACOSCC=11 and CCOMCC=61) BASE
Left join 
(Select CPROCC, CSUCCC,COPECC,NCTOCC, ACOSCC, NCOMCC, sum(IMPMCC) "I15" from MERFL.MER331F1 
where CPROCC=17 and ACOSCC=11 and CCOMCC=61 and CCONCC=15
group by CPROCC, CSUCCC,COPECC,NCTOCC, ACOSCC, NCOMCC) C15 on BASE.CPROCC = C15.CPROCC and BASE.CSUCCC=C15.CSUCCC and BASE.COPECC=C15.COPECC and BASE.NCTOCC=C15.NCTOCC and  BASE.ACOSCC=C15.ACOSCC and BASE.NCOMCC=C15.NCOMCC
left join
(Select CPROCC, CSUCCC,COPECC,NCTOCC, ACOSCC, NCOMCC, sum(IMPMCC) "I24" from MERFL.MER331F1 
where CPROCC=17 and ACOSCC=11 and CCOMCC=61 and CCONCC=24
group by CPROCC, CSUCCC,COPECC,NCTOCC, ACOSCC, NCOMCC
order by CPROCC, CSUCCC,COPECC,NCTOCC) C24 on BASE.CPROCC = C24.CPROCC and BASE.CSUCCC=C24.CSUCCC and BASE.COPECC=C24.COPECC and BASE.NCTOCC=C24.NCTOCC and  BASE.ACOSCC=C24.ACOSCC and BASE.NCOMCC=C24.NCOMCC
left join
(Select CPROCC, CSUCCC,COPECC,NCTOCC, ACOSCC, NCOMCC, sum(IMPMCC) "I65" from MERFL.MER331F1 
where CPROCC=17 and ACOSCC=11 and CCOMCC=61 and CCONCC=65
group by CPROCC, CSUCCC,COPECC,NCTOCC, ACOSCC, NCOMCC) C65 on BASE.CPROCC = C65.CPROCC and BASE.CSUCCC=C65.CSUCCC and BASE.COPECC=C65.COPECC and BASE.NCTOCC=C65.NCTOCC and  BASE.ACOSCC=C65.ACOSCC and BASE.NCOMCC=C65.NCOMCC
left join
(Select CPROCC, CSUCCC,COPECC,NCTOCC, ACOSCC, NCOMCC, sum(IMPMCC) "I66" from MERFL.MER331F1 
where CPROCC=17 and ACOSCC=11 and CCOMCC=61 and CCONCC=66
group by CPROCC, CSUCCC,COPECC,NCTOCC, ACOSCC, NCOMCC) C66 on BASE.CPROCC = C66.CPROCC and BASE.CSUCCC=C66.CSUCCC and BASE.COPECC=C66.COPECC and BASE.NCTOCC=C66.NCTOCC and  BASE.ACOSCC=C66.ACOSCC and BASE.NCOMCC=C66.NCOMCC
order by BASE.CPROCC, BASE.CSUCCC, BASE.COPECC, BASE.NCTOCC, BASE.ACOSCC, BASE.NCOMCC
*/
Select * from TOEPFERDB.TBLARTICULOSDATOS where IDARTICULO in (1970) 
--Select * from PROVFL.ACD7REP where NINGX7=707248
--Update PROVFL.ACD7REP set IMPOX7=-IMPOX7, IMPDX7=-IMPDX7 where NINGX7<>707248 and PRECX7<0
--Select DISTINCT A.NCOMR1 from MERFL.MER42CF1 A inner join MERFL.MER42CF1 B on A.NCAIR1=B.NCAIR1 and A.CUITR1<>B.CUITR1


--Select * from TOEPFERDB.TBLOBRAPAGOS where IDPIC=5618
--Update TOEPFERDB.TBLVALESFIRMAS set HKEY='A_MANO' where IDVALE in (Select IDVALE from TOEPFERDB.TBLVALESCABECERA C where CDVALE in ('AJS', 'XJS', 'VRS', 'XRS')) and SECUENCIA=1 and HKEY is Null
--Select * from TOEPFERDB.TBLVALESFIRMAS where IDVALE=12635

--Update TOEPFERDB.TBLCTZFIRMAS set HKEY = Null, FECHAFIRMA=Null where IDCOTIZACION=5618

-- Consulta sobre saldos pendientes de los PICs

Select  C.IDCOTIZACION IDPIC, 
        O.CDOBRA,
        C.IDPROVEEDOR PROVEEDOR, 
        E.DSEMPRESA,     
        C.CDMONEDA MONEDA,        
        Sum(FLOAT(D.IMPORTEPESOS)/100) "IMPORTE PIC ARS",
        Sum(FLOAT(D.IMPORTEPESOSFACTURADO)/100) "IMPORTE FACTURADO ARS",
        Sum(FLOAT(D.IMPORTEPESOS-D.IMPORTEPESOSFACTURADO)/100) "SALDO ARS",
        Sum(FLOAT(D.IMPORTEDOLARES)/100) "IMPORTE PIC USD",
        Sum(FLOAT(D.IMPORTEDOLARESFACTURADO)/100) "IMPORTE FACTURADO USD",
        Sum(FLOAT(D.IMPORTEDOLARES-D.IMPORTEDOLARESFACTURADO)/100) "SALDO USD"
    from TOEPFERDB.TBLCTZCABECERA C     
    inner join TOEPFERDB.TBLCTZDETALLE D on C.IDCOTIZACION=D.IDCOTIZACION    
    inner join TOEPFERDB.VWEMPRESAS E on E.IDEMPRESA=C.IDPROVEEDOR
    left join TOEPFERDB.TBLDATOSOBRAS O on O.IDOBRA=C.IDOBRA -- and O.TIPOGASTO='M'
    where 
        MOMENTO>=20100101000000 
        and MOMENTO<=20131231000000 
        and C.ESTADO not in ('F', 'R')
        and O.CDOBRA='0668'         
        --and C.IDDIVISION IN (3) --BAHIA
        --and C.IDDIVISION IN (1) --Exportacion
        --and C.IDDIVISION IN (2, 4) -ARROYO / TRANSITO
    group by C.IDCOTIZACION, O.CDOBRA, C.IDPROVEEDOR, E.DSEMPRESA, C.CDMONEDA

-----------------------------------------------
Select AFE.IDAFE, 
CDAFE, 
IDDIVISION, 
CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(concat(CONCAT(substr(MOMENTO,7, 2), '/'), substr(MOMENTO,5, 2)), '/'), substr(MOMENTO,1, 4)), ' '), substr(MOMENTO, 9, 2)), ':'), substr(MOMENTO, 11, 2)), ':'), substr(MOMENTO, 13, 2)) CARGA,
CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(concat(CONCAT(substr(INICIO,7, 2), '/'), substr(INICIO,5, 2)), '/'), substr(INICIO,1, 4)), ' '), substr(INICIO, 9, 2)), ':'), substr(INICIO, 11, 2)), ':'), substr(INICIO, 13, 2)) INICIO,
CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(concat(CONCAT(substr(FIN,7, 2), '/'), substr(FIN,5, 2)), '/'), substr(FIN,1, 4)), ' '), substr(FIN, 9, 2)), ':'), substr(FIN, 11, 2)), ':'), substr(FIN, 13, 2)) FIN
from 
(Select * from TOEPFERDB.TBLDATOSAFE where MOMENTO>=20120101000000 and CONFIRMADO='A') AFE
left join (Select IDAFE, MIN(FECHAFIRMA) INICIO from TOEPFERDB.TBLAFEFIRMAS group by IDAFE) PFirma on AFE.IDAFE=PFIRMA.IDAFE
left join (Select IDAFE, MAX(FECHAFIRMA) FIN from TOEPFERDB.TBLAFEFIRMAS group by IDAFE) UFirma on AFE.IDAFE=UFIRMA.IDAFE


Insert into MERFL.MER517F3 values (46, 46)

Select IDROL, DSROL from TOEPFERDB.TBLROLES where IDPRODUCTO=2
Select CDUSUARIO, DSROL from TOEPFERDB.TBLROLESUSUARIOS A inner join TOEPFERDB.TBLROLES B on A.IDROL=B.IDROL order by CDUSUARIO

Select * from TOEPFERDB.TBLUSUARIOPERMISOS where IDRECURSO=20
Select * from QRY.LISTPROVET where LTVEND in (26086, 26087)
Select count(*) CANT from TOEPFERDB.TBLCTZDETALLE where FACTURADO <> CANTIDAD and IDCOTIZACION=12865

Delete from TOEPFERDB.TBLPOLIZASCAUCION WHERE IDPEDIDO = 4415

Select * from PROVFL.ACDSREP where DSDUST='FAC' and DSOPR1=11667 and DSCRDT between 1120101 and 1121231 order by DSCRDT
Select * from PROVFL.ACDSREP where DSDUST='NCR' and DSOPR1=11667 and DSCRDT between 1120101 and 1131231 order by DSCRDT


Delete from QRY.LISTPROVET where LTVEND in (26086, 26087)


Insert into TOEPFERDB.TBLREMPIC values(0, 4946, 0, 0)
Insert into TOEPFERDB.TBLREMPIC values(0, 5420, 0, 0)
Insert into TOEPFERDB.TBLREMPIC values(0, 6226, 0, 0)
Insert into TOEPFERDB.TBLREMPIC values(0, 7016, 0, 0)
Insert into TOEPFERDB.TBLREMPIC values(0, 8417, 0, 0)
Insert into TOEPFERDB.TBLREMPIC values(0, 3530, 0, 0)
Insert into TOEPFERDB.TBLREMPIC values(0, 3541, 0, 0)
Insert into TOEPFERDB.TBLREMPIC values(0, 3619, 0, 0)
Insert into TOEPFERDB.TBLREMPIC values(0, 3744, 0, 0)
Insert into TOEPFERDB.TBLREMPIC values(0, 3786, 0, 0)
Insert into TOEPFERDB.TBLREMPIC values(0, , 0, 0)


SELECT * FROM SYSFL.SYS001F1 WHERE SYOBJE ='MER515' and SYFDPR=20101116

Select * from TOEPFERDB.TBLCTZDETALLE where IDARTICULO in (9119)
Select * from TOEPFERDB.TBLCTZCABECERA where IDCOTIZACION in (7960)


Select * from TOEPFERDB.TBLARTVALUACION where IDDIVISION=4 and IDARTICULO=9119 order by FECHACIERRE
Select * from TOEPFERDB.TBLREMPIC where IDPIC=5656

Select * from PROVFL.ACD7REP where COTIX7=11777
Select * from TOEPFERDB.TBLDATOSOBRAS where CDOBRA like '%ASMAN%'
Select COTIX7, ARTIX7, sum(IMPOX7) IMPORTEFAC, sum(CANTX7) CANTFAC from PROVFL.ACD7REP where COTIX7=11777 group by COTIX7, ARTIX7


Select CAB.IDCOTIZACION, CAB.IDOBRA, RP.IDREMITO, DET.IDARTICULO, DET.CANTIDAD, RDET.EXISTENCIA, RDET.SOBRANTE, BIENUSO, TIPOCATEGORIA
from TOEPFERDB.TBLCTZCABECERA CAB
inner join TOEPFERDB.TBLCTZDETALLE DET on CAB.IDCOTIZACION=DET.IDCOTIZACION
inner join (select idremito, idpic, idarticulo, sum(cantidad) from TOEPFERDB.TBLREMPIC group by idremito, idpic, idarticulo) RP on RP.IDPIC=DET.IDCOTIZACION and RP.IDARTICULO=DET.IDARTICULO
inner join TOEPFERDB.TBLREMDETALLE RDET on RDET.IDREMITO=RP.IDREMITO and RDET.IDARTICULO=DET.IDARTICULO
inner join TOEPFERDB.TBLARTICULOS ART on DET.IDARTICULO=ART.IDARTICULO
inner join TOEPFERDB.TBLARTCATEGORIAS CAT on CAT.IDCATEGORIA=ART.IDCATEGORIA
where ART.BIENUSO='N' and IDOBRA=243




Update TOEPFERDB.TBLARTICULOS set IDCATEGORIA=11 where IDARTICULO=11598

Select * from TOEPFERDB.TBLARTCATEGORIAS


 SELECT DISTINCT CTC.IDCONTRATO IDDOCUMENTO, 'CTC' TIPO, CTC.IDPEDIDO AS idpedido, CTC.IDOBRA AS IDOBRA, CTC.CDCONTRATO CDDOCUMENTO, C.cdobra CDOBRA, PCT.CDPEDIDO CDPEDIDO, PCT.IDPROVEEDOR IDPROVEEDOR,EMP.DSEMPRESA DSPROVEEDOR, '' PTO  
 FROM TOEPFERDB.TBLOBRACTCAJUSTES AC 	
 	INNER JOIN TOEPFERDB.TBLOBRACTCAJUSTESFIRMAS AF ON AC.IDAJUSTE=AF.IDAJUSTE 		
 	INNER JOIN 			( SELECT IDAJUSTE, MIN(SECUENCIA) minSec 					
 							FROM TOEPFERDB.TBLOBRACTCAJUSTESFIRMAS 
 							WHERE HKEY IS NULL OR HKEY = '' 						
 							GROUP BY IDAJUSTE 	) US 		ON US.IDAJUSTE=AF.IDAJUSTE AND AF.SECUENCIA=US.MINSEC 		
 	INNER JOIN TOEPFERDB.TBLOBRACONTRATOS CTC on CTC.IDCONTRATO=AC.IDCONTRATO 		
 	LEFT JOIN TOEPFERDB.TBLDATOSOBRAS C on C.IDOBRA = CTC.IDOBRA		
 	LEFT JOIN TOEPFERDB.TBLPCTCABECERA PCT on CTC.IDPEDIDO = PCT.IDPEDIDO        
 	LEFT JOIN TOEPFERDB.VWEMPRESAS EMP on EMP.IDEMPRESA = PCT.IDPROVEEDOR 			
 WHERE AF.CDUSUARIO='LAM' 
 		AND (HKEY IS NULL OR HKEY='') 
 --		AND APLICADO='N' 


Select * from MERFL.MER517F3

Select * from MERFL.MER5F1F1

Select Sc.IDDIVISION, SC.IDARTICULO, Sc.STOCKDISPONIBLE,  FAC.CANT_ACD7_SObra, CANT_ACD7_CObra, FAC.CANT_ACD7_SObra_RECALCULADA  from 
(Select * from TOEPFERDB.TBLARTVALUACION where FECHACIERRE=20131130) SC 
left join
(
Select CAB.IDDIVISION, 
DET.IDARTICULO, 
sum(CANTFAC) CANT_ACD7_SObra,
sum((DET.CANTIDAD*FAC.IMPORTEFAC*100)/DET.IMPORTEPESOS) CANT_ACD7_SObra_RECALCULADA
 from
(Select COTIX7, ARTIX7, sum(IMPOX7) IMPORTEFAC, sum(CANTX7) CANTFAC from PROVFL.ACD7REP group by COTIX7, ARTIX7) FAC
inner join TOEPFERDB.TBLCTZDETALLE DET on DET.IDCOTIZACION=FAC.COTIX7 and DET.IDARTICULO=FAC.ARTIX7
inner join TOEPFERDB.TBLCTZCABECERA CAB on CAB.IDCOTIZACION=FAC.COTIX7
where CAB.MOMENTO>=20110101000000
and CAB.IDOBRA=0
group by CAb.IDDIVISION, 
DET.IDARTICULO
) FAC on SC.IDDIVISION=FAC.IDDIVISION and SC.IDARTICULO=FAC.IDARTICULO
left join
(
Select CAB.IDDIVISION, 
DET.IDARTICULO, 
sum(CANTFAC) CANT_ACD7_CObra
 from
(Select COTIX7, ARTIX7, sum(IMPOX7) IMPORTEFAC, sum(CANTX7) CANTFAC from PROVFL.ACD7REP group by COTIX7, ARTIX7) FAC
inner join TOEPFERDB.TBLCTZDETALLE DET on DET.IDCOTIZACION=FAC.COTIX7 and DET.IDARTICULO=FAC.ARTIX7
inner join TOEPFERDB.TBLCTZCABECERA CAB on CAB.IDCOTIZACION=FAC.COTIX7
where CAB.MOMENTO>=20110101000000
and CAB.MOMENTO<=20120930235959
and CAB.IDOBRA<>0
group by CAb.IDDIVISION, 
DET.IDARTICULO
) FAC2 on SC.IDDIVISION=FAC2.IDDIVISION and SC.IDARTICULO=FAC2.IDARTICULO


Select SF.IDDIVISION, SF.IDARTICULO, STOCK_FISICO, STOCKDISPONIBLE, CANT_ACTUAL, CANT_RECALCULADA from 
(Select IDDIVISION, IDARTICULO, sum(EXISTENCIA) STOCK_FISICO from TOEPFERDB.TBLCIERRESARTICULOS2 CA
inner join TOEPFERDB.TBLALMACENES AL on CA.IDALMACEN = AL.IDALMACEN
where FECHACIERRE=20131130
group by IDDIVISION, IDARTICULO) SF
left join (Select * from TOEPFERDB.TBLARTVALUACION where FECHACIERRE=20131130) SC on SF.IDDIVISION=SC.IDDIVISION and SF.IDARTICULO=SC.IDARTICULO
left join
(
Select CAb.IDDIVISION, 
DET.IDARTICULO, 
sum(CANTFAC) CANT_ACTUAL,
sum((DET.CANTIDAD*FAC.IMPORTEFAC*100)/DET.IMPORTEPESOS) CANT_RECALCULADA from
(Select COTIX7, ARTIX7, sum(IMPOX7) IMPORTEFAC, sum(CANTX7) CANTFAC from PROVFL.ACD7REP group by COTIX7, ARTIX7) FAC
inner join TOEPFERDB.TBLCTZDETALLE DET on DET.IDCOTIZACION=FAC.COTIX7 and DET.IDARTICULO=FAC.ARTIX7
inner join TOEPFERDB.TBLCTZCABECERA CAB on CAB.IDCOTIZACION=FAC.COTIX7
where CAB.MOMENTO>=20110101000000
--and CAB.IDOBRA=0
group by CAb.IDDIVISION, 
DET.IDARTICULO
) RECALCULO on SF.IDDIVISION=RECALCULO.IDDIVISION and SF.IDARTICULO=RECALCULO.IDARTICULO
where SF.IDARTICULO=5575
--where CANT_ACTUAL is Null and CANT_RECALCULADA is not Null
--where CANT_ACTUAL is Null and CANT_RECALCULADA is Null and STOCKDISPONIBLE<>0 and STOCKDISPONIBLE<>STOCK_FISICO



Select 
DET.IDCOTIZACION,
DET.IDARTICULO, 
R_EX,
R_SO
from
TOEPFERDB.TBLCTZDETALLE DET 
inner join TOEPFERDB.TBLCTZCABECERA CAB on CAB.IDCOTIZACION=DET.IDCOTIZACION
inner join (
Select IDPIC, RD.IDARTICULO, SUM(EXISTENCIA) R_EX, SUM(SOBRANTE) R_SO from TOEPFERDB.TBLREMDETALLE RD
left join TOEPFERDB.TBLREMPIC RP on Rd.IDREMITO=RP.IDREMITO and RP.IDARTICULO=RD.IDARTICULO
group by IDPIC, RD.IDARTICULO
) RP on RP.IDPIC=DET.IDCOTIZACION and DET.IDARTICULO=RP.IDARTICULO
where CAB.MOMENTO>=20110101000000
and CAB.MOMENTO<=20121130235959
and CAB.IDOBRA<>0
and R_EX > 0


Select DET.IDCOTIZACION, DET.IDARTICULO, CAB.MOMENTO, DET.IMPORTEPESOS, IMPOFAC from TOEPFERDB.TBLCTZCABECERA CAB
inner join TOEPFERDB.TBLCTZDETALLE DET on CAB.IDCOTIZACION=DET.IDCOTIZACION
inner join (Select COTIX7, ARTIX7, SUM(IMPOX7*100) IMPOFAC FROM PROVFL.ACD7REP group by COTIX7, ARTIX7) FAC on FAC.COTIX7=DET.IDCOTIZACION and FAC.ARTIX7=DET.IDARTICULO
INNER JOIN toepferdb.tblarticulos ART
               ON ART.idarticulo = DET.idarticulo
INNER JOIN toepferdb.tblartcategorias CAT
               ON CAT.idcategoria = ART.idcategoria
where CAB.ESTADO in  ('2')
and CDMONEDA='P'
and CAB.MOMENTO>=20110101000000
and IMPOFAC < DET.IMPORTEPESOS
and TIPOCATEGORIA='B'
and ABS(1-(IMPOFAC/DET.IMPORTEPESOS)) > 0.05 