
--SELECT * FROM DB2ADMIN.MERMASAUTOMATICAS --where IDCAMION='0000000519' and CDPRODUCTO=19

--Update DB2ADMIN.MERMASAUTOMATICAS set SQMERMAAUTO=SQMERMAAUTO*10 where IDCAMION='0000000163' and CDPRODUCTO=19
--Update DB2ADMIN.MERMASAUTOMATICAS set SQMERMAAUTO=SQMERMAAUTO*10 where IDCAMION='0000000495' and CDPRODUCTO=19
--Select * from camiones
--Select * from camionesdescarga

--Select * from Hcamionesdescarga where nucartaporte='000537579577'

--Select CDRUBRO, count(*) from DB2ADMIN.MERMASAUTOMATICAS group by CDRUBRO
--Select * from MERMASAUTOMATICAS where CDRUBRO=1

--ALTER TABLE "DB2ADMIN"."MERMASAUTOMATICAS" DROP PRIMARY KEY
--ALTER TABLE "DB2ADMIN"."MERMASAUTOMATICAS" ADD PRIMARY KEY("IDCAMION", "NUCARTAPORTE", "SQMERMAAUTO", "CDRUBRO")